import express from 'express';
import crypto from 'node:crypto';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcrypt';
import rateLimit from 'express-rate-limit';
import {RetailError,requireValue,text,integer,cents,total,quantities,dateRange,localDay} from './retail-domain.js';
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
export async function setupRetail(db){
 await db.collection('retail_shifts').createIndex({profileId:1},{unique:true,partialFilterExpression:{status:'open'}});
 await db.collection('retail_sales').createIndex({shiftId:1,createdAt:-1});
 await db.collection('retail_sales').createIndex({createdAt:1});
 await db.collection('retail_tips').createIndex({shiftId:1,createdAt:1});
 await db.collection('retail_movements').createIndex({productId:1,createdAt:-1});
}
export function retailRouter({getDB,client,authenticateToken,isAdmin,secret,masterPassword=()=>process.env.RETAIL_MASTER_PASSWORD||process.env.ADMIN_PASS,masterHash=()=>process.env.RETAIL_MASTER_PASSWORD_HASH}){
 const router=express.Router();
 router.use((req,res,next)=>{res.set('Cache-Control','private, no-store');next();},authenticateToken,(req,res,next)=>isAdmin(req)?next():res.sendStatus(403));
 const labels=body=>{requireValue(Array.isArray(body.labels||[])&&(body.labels||[]).length<=8,'Add up to 8 filter labels.');return {unitLabel:text(body.unitLabel||'item','Packaging label',40),labels:[...new Set((body.labels||[]).map(v=>text(v,'Filter label',40)))]};};
 const col=name=>getDB().collection('retail_'+name);
 const run=fn=>(req,res,next)=>Promise.resolve(fn(req,res)).catch(next);
 const managerValid=req=>{try{const t=jwt.verify(req.get('X-Retail-Manager')||'',secret,{algorithms:['HS256'],audience:'retail-reports'});return t.sub===req.user.id&&t.session===hash(req.get('Authorization')||'');}catch{return false;}};
 const manager=(req,res,next)=>managerValid(req)?next():res.status(403).json({error:'Unlock manager reports first.'});
 const actor=req=>({actorId:req.user.id,at:new Date()});
 // Every operation and its stock ledger entries commit together, including the retry receipt.
 async function write(req,kind,fn){
  const key=text(req.body?.requestId,'Request ID',80);requireValue(/^[\w-]{8,80}$/.test(key),'Invalid request ID.');const id=kind+':'+key,fingerprint=hash(JSON.stringify([req.user.id,req.originalUrl,req.body]));
  const session=client.startSession();let result;
  try{await session.withTransaction(async()=>{const old=await col('operations').findOne({_id:id},{session});if(old){requireValue(old.fingerprint===fingerprint,'This request ID was already used for different details.',409);result=old.result;return;}result=await fn(session);await col('operations').insertOne({_id:id,fingerprint,result,...actor(req)},{session});});return result;}
  catch(e){if(e.code===11000){const old=await col('operations').findOne({_id:id});if(old&&old.fingerprint===fingerprint)return old.result;throw new RetailError('Another update just completed. Refresh and try again.',409);}throw e;}
  finally{await session.endSession();}
 }
 async function shift(id,session,req){const s=await col('shifts').findOne({_id:id},{session});requireValue(s,'Shift not found.',404);requireValue(s.status==='open'||managerValid(req),'This shift is closed. A manager must unlock it to correct sales.',409);await col('shifts').updateOne({_id:id},{$inc:{revision:1}},{session});return s;}
 async function move(product,delta,reason,req,session,saleId=null){if(!delta)return;integer(delta,'Stock change',{signed:true});const after=integer(product.stock+delta,'Remaining stock',{zero:true});const updated=await col('products').updateOne({_id:product._id,stock:product.stock,revision:product.revision},{$set:{stock:after,updatedAt:new Date()},$inc:{revision:1}},{session});requireValue(updated.modifiedCount===1,'Stock changed. Refresh and retry.',409);await col('movements').insertOne({_id:crypto.randomUUID(),productId:product._id,delta,before:product.stock,after,reason,saleId,createdAt:new Date(),...actor(req)},{session});}
 router.post('/manager/unlock',rateLimit({windowMs:15*60*1000,max:10,standardHeaders:true,legacyHeaders:false}),run(async(req,res)=>{
  const password=typeof req.body.password==='string'?req.body.password:'';requireValue(password.length>0&&password.length<=1024,'Enter the master password.',401);const stored=masterHash(),plain=masterPassword();requireValue(stored||plain,'A master password must be configured by the site owner.',503);
  const ok=stored?await bcrypt.compare(password,stored):crypto.timingSafeEqual(Buffer.from(hash(password)),Buffer.from(hash(plain)));requireValue(ok,'Incorrect master password.',401);
  res.json({token:jwt.sign({session:hash(req.get('Authorization')||'')},secret,{subject:req.user.id,audience:'retail-reports',expiresIn:'15m'}),expiresIn:900});
 }));
 router.get('/profiles',run(async(req,res)=>res.json(await col('profiles').find({active:true}).sort({name:1}).toArray())));
 router.post('/profiles',manager,run(async(req,res)=>res.json(await write(req,'profile',async session=>{const p={_id:crypto.randomUUID(),name:text(req.body.name,'Staff name'),role:['staff','manager'].includes(req.body.role)?req.body.role:'staff',active:true,createdAt:new Date()};await col('profiles').insertOne(p,{session});return p;}))));
 router.patch('/profiles/:id',manager,run(async(req,res)=>res.json(await write(req,'profile-edit',async session=>{const p=await col('profiles').findOne({_id:req.params.id},{session});requireValue(p,'Profile not found.',404);requireValue(typeof req.body.active==='boolean','Choose profile availability.');if(!req.body.active)requireValue(!await col('shifts').findOne({profileId:p._id,status:'open'},{session}),'Close this staff member’s shift before archiving their profile.',409);await col('profiles').updateOne({_id:p._id},{$set:{active:req.body.active}},{session});return {ok:true};}))));
 router.get('/products',run(async(req,res)=>res.json(await col('products').find({}).sort({name:1}).toArray())));
 router.post('/products',run(async(req,res)=>res.json(await write(req,'product',async session=>{requireValue(['drinks','accessories'].includes(req.body.category),'Choose drinks or accessories.');const p={_id:crypto.randomUUID(),name:text(req.body.name,'Product name'),category:req.body.category,...labels(req.body),priceCents:cents(req.body.price),stock:0,active:true,revision:0,createdAt:new Date(),updatedAt:new Date()};await col('products').insertOne(p,{session});return p;}))));
 router.patch('/products/:id',run(async(req,res)=>res.json(await write(req,'product-edit',async session=>{const p=await col('products').findOne({_id:req.params.id},{session});requireValue(p,'Product not found.',404);requireValue(p.revision===req.body.revision,'Product changed. Refresh and retry.',409);requireValue(['drinks','accessories'].includes(req.body.category)&&typeof req.body.active==='boolean','Choose category and availability.');const changes={name:text(req.body.name,'Product name'),category:req.body.category,...labels(req.body),priceCents:cents(req.body.price),active:req.body.active,updatedAt:new Date()};await col('products').updateOne({_id:p._id},{$set:changes,$inc:{revision:1}},{session});return {...p,...changes,revision:p.revision+1};}))));
 router.post('/products/:id/stock',run(async(req,res)=>res.json(await write(req,'stock',async session=>{const p=await col('products').findOne({_id:req.params.id},{session});requireValue(p,'Product not found.',404);const delta=integer(req.body.delta,'Stock adjustment',{signed:true});requireValue(delta!==0,'Enter a non-zero adjustment.');requireValue(p.stock+delta>=0,'There is not enough stock.',409);await move(p,delta,text(req.body.reason,'Stock adjustment reason',200),req,session);return {stock:p.stock+delta};}))));
 router.get('/products/:id/movements',run(async(req,res)=>res.json(await col('movements').find({productId:req.params.id}).sort({createdAt:-1}).limit(50).toArray())));
 router.post('/shifts',run(async(req,res)=>res.json(await write(req,'shift',async session=>{const p=await col('profiles').findOne({_id:req.body.profileId,active:true},{session});requireValue(p,'Choose an active staff profile.');const existing=await col('shifts').findOne({profileId:p._id,status:'open'},{session});if(existing)return existing;await col('profiles').updateOne({_id:p._id},{$set:{lastShiftAt:new Date()}},{session});const s={_id:crypto.randomUUID(),profileId:p._id,staffName:p.name,staffRole:p.role,status:'open',openedAt:new Date(),revision:0,...actor(req)};await col('shifts').insertOne(s,{session});return s;}))));
 router.get('/shifts/:id',run(async(req,res)=>{const s=await col('shifts').findOne({_id:req.params.id});requireValue(s,'Shift not found.',404);const sales=await col('sales').find({shiftId:s._id}).sort({createdAt:-1}).toArray();const tips=await col('tips').find({shiftId:s._id}).sort({createdAt:-1}).toArray();res.json({...s,sales,tips,salesCents:sales.reduce((n,s)=>n+s.totalCents,0),tipsCents:tips.reduce((n,t)=>n+t.amountCents,0),saleCount:sales.filter(s=>!s.voided).length});}));
 router.post('/shifts/:id/close',run(async(req,res)=>res.json(await write(req,'shift-close',async session=>{const s=await shift(req.params.id,session,req);requireValue(s.status==='open','Shift is already closed.',409);await col('shifts').updateOne({_id:s._id},{$set:{status:'closed',closedAt:new Date()}},{session});return {ok:true};}))));
 router.post('/shifts/:id/tips',run(async(req,res)=>res.json(await write(req,'tip',async session=>{const s=await shift(req.params.id,session,req);requireValue(s.status==='open','Add tips before closing the shift.',409);const amount=cents(req.body.amount);requireValue(amount>0,'Enter a tip above zero.');const t={_id:crypto.randomUUID(),shiftId:s._id,profileId:s.profileId,staffName:s.staffName,amountCents:amount,createdAt:new Date(),...actor(req)};await col('tips').insertOne(t,{session});return t;}))));
 async function saleLines(input,old,req,session,saleId){const next=quantities(input),previous=new Map((old?.lines||[]).map(l=>[l.productId,l]));const lines=[];for(const id of new Set([...next.keys(),...previous.keys()])){const p=await col('products').findOne({_id:id},{session});requireValue(p,'Product no longer exists.',409);const count=next.get(id)||0,oldLine=previous.get(id),delta=(oldLine?.quantity||0)-count;const quote=input.find(l=>l.productId===id)?.expectedPriceCents;if(count&&!oldLine&&quote!==undefined)requireValue(quote===p.priceCents,`${p.name}: price changed. Refresh the catalogue before selling.`,409);requireValue(!count||p.active||count<=(oldLine?.quantity||0),'This product is archived.',409);requireValue(p.stock+delta>=0,`${p.name}: only ${p.stock+(oldLine?.quantity||0)} units available.`,409);if(delta)await move(p,delta,old?'Sale correction':'Cash sale',req,session,saleId);if(count)lines.push({productId:id,name:oldLine?.name||p.name,category:oldLine?.category||p.category,unitLabel:oldLine?.unitLabel||p.unitLabel||'item',quantity:count,priceCents:oldLine?.priceCents??p.priceCents});}total(lines);return lines;}
 router.post('/sales',run(async(req,res)=>res.json(await write(req,'sale',async session=>{const s=await shift(req.body.shiftId,session,req);requireValue(s.status==='open','Start an open shift before selling.',409);requireValue(req.body.lines?.length,'Add a product first.');const id=crypto.randomUUID(),lines=await saleLines(req.body.lines,null,req,session,id);const sale={_id:id,receipt:localDay().replaceAll('-','')+'-'+id.slice(0,8).toUpperCase(),shiftId:s._id,profileId:s.profileId,staffName:s.staffName,staffRole:s.staffRole,lines,totalCents:total(lines),revision:1,voided:false,createdAt:new Date(),...actor(req)};await col('sales').insertOne(sale,{session});return sale;}))));
 router.patch('/sales/:id',run(async(req,res)=>res.json(await write(req,'sale-edit',async session=>{const old=await col('sales').findOne({_id:req.params.id},{session});requireValue(old,'Sale not found.',404);requireValue(old.revision===req.body.revision,'This sale changed. Reopen it before editing.',409);await shift(old.shiftId,session,req);const reason=text(req.body.reason,'Correction reason',200);const lines=await saleLines(req.body.lines,old,req,session,old._id);const updated={...old,lines,totalCents:total(lines),revision:old.revision+1,voided:lines.length===0,updatedAt:new Date()};await col('sale_history').insertOne({_id:crypto.randomUUID(),saleId:old._id,before:old,after:updated,reason,...actor(req)},{session});await col('sales').replaceOne({_id:old._id,revision:old.revision},updated,{session});return {...updated,cashDifferenceCents:updated.totalCents-old.totalCents};}))));
 router.get('/reports',manager,run(async(req,res)=>{const {start,end}=dateRange(req.query.from||localDay(),req.query.to||localDay());const match={createdAt:{$gte:start,$lt:end}};const [daily,staff,products,tipRows,shifts]=await Promise.all([
  col('sales').aggregate([{$match:match},{$group:{_id:{$dateToString:{date:'$createdAt',format:'%Y-%m-%d',timezone:'Europe/Madrid'}},salesCents:{$sum:'$totalCents'},count:{$sum:{$cond:['$voided',0,1]}}}},{$sort:{_id:1}}]).toArray(),
  col('sales').aggregate([{$match:match},{$group:{_id:'$profileId',name:{$last:'$staffName'},role:{$last:'$staffRole'},salesCents:{$sum:'$totalCents'},count:{$sum:{$cond:['$voided',0,1]}}}}]).toArray(),
  col('sales').aggregate([{$match:match},{$unwind:'$lines'},{$group:{_id:'$lines.productId',name:{$last:'$lines.name'},units:{$sum:'$lines.quantity'},salesCents:{$sum:{$multiply:['$lines.quantity','$lines.priceCents']}}}},{$sort:{salesCents:-1}}]).toArray(),
  col('tips').aggregate([{$match:match},{$group:{_id:'$profileId',name:{$last:'$staffName'},tipsCents:{$sum:'$amountCents'},entries:{$sum:1}}}]).toArray(),
  col('shifts').find({openedAt:{$lt:end},$or:[{closedAt:{$gte:start}},{status:'open'}]}).sort({openedAt:-1}).limit(500).toArray()
 ]);for(const t of tipRows){let row=staff.find(s=>s._id===t._id);if(!row){row={_id:t._id,name:t.name,salesCents:0,count:0};staff.push(row);}row.tipsCents=t.tipsCents;row.tipEntries=t.entries;}res.json({timezone:'Europe/Madrid',from:req.query.from,to:req.query.to,daily,staff,products,shifts,totals:{salesCents:daily.reduce((n,d)=>n+d.salesCents,0),saleCount:daily.reduce((n,d)=>n+d.count,0),tipsCents:tipRows.reduce((n,d)=>n+d.tipsCents,0)}});
 }));
 router.use((err,req,res,next)=>{if(err instanceof RetailError)return res.status(err.status).json({error:err.message});console.error('Retail request failed',err.name,err.code||'');res.status(500).json({error:'Could not save this operation. Retry using the same screen; duplicate sales are prevented.'});});
 return router;
}
