export class RetailError extends Error { constructor(message,status=400){super(message);this.status=status;} }
export const requireValue=(ok,message,status=400)=>{if(!ok)throw new RetailError(message,status);};
export function text(value,label,max=120){requireValue(typeof value==='string'&&value.trim().length>0&&value.trim().length<=max,`${label} is required (up to ${max} characters).`);return value.trim();}
export function integer(value,label,{zero=false,signed=false}={}){requireValue(Number.isSafeInteger(value)&&(signed||value>=(zero?0:1)),`${label} must be ${signed?'a whole number':zero?'zero or a positive whole number':'a positive whole number'}.`);return value;}
export function cents(value){const s=String(value??'').trim();requireValue(/^\d+(?:[.,]\d{1,2})?$/.test(s),'Enter a price with no more than two decimal places.');const [a,b='']=s.replace(',','.').split('.');return integer(Number(a)*100+Number(b.padEnd(2,'0')),'Price',{zero:true});}
export function total(lines){return integer(lines.reduce((sum,l)=>sum+integer(l.quantity,'Quantity')*integer(l.priceCents,'Price',{zero:true}),0),'Total',{zero:true});}
export function quantities(lines){requireValue(Array.isArray(lines)&&lines.length<=200,'Choose up to 200 products.');const result=new Map();for(const l of lines){const id=text(l.productId,'Product',80);requireValue(!result.has(id),'A product may only appear once in a sale.');result.set(id,integer(l.quantity,'Quantity'));}return result;}
const dayFmt=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit'});
export function localDay(date=new Date()){const p=Object.fromEntries(dayFmt.formatToParts(date).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`;}
function midnight(day){requireValue(/^\d{4}-\d{2}-\d{2}$/.test(day),'Choose a valid date.');const utc=Date.parse(day+'T00:00:00Z');requireValue(Number.isFinite(utc)&&new Date(utc).toISOString().startsWith(day),'Choose a valid date.');let time=utc;for(let i=0;i<3;i++){const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(time)).map(x=>[x.type,x.value]));const represented=Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,+p.second);time+=utc-represented;}return new Date(time);}
export function dateRange(from,to){const start=midnight(from),last=midnight(to);requireValue(last>=start&&last-start<=366*86400000,'Choose a range of up to one year.');const tomorrow=new Date(Date.parse(to+'T00:00:00Z')+86400000).toISOString().slice(0,10);return {start,end:midnight(tomorrow)};}
