import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';import request from 'supertest';import bcrypt from 'bcrypt';import {ObjectId} from 'mongodb';import {memberAccountRouter} from '../member-account.js';import {isStaff} from '../staff-auth.js';
import crypto from 'node:crypto';import {encodeCBOR} from '@levischuck/tiny-cbor';import * as realWA from '@simplewebauthn/server';
const match=(doc,q)=>Object.entries(q).every(([k,v])=>v&&v.$gt?doc[k]>v.$gt:String(doc[k])===String(v));
async function fixture(real=false){const id=new ObjectId(),other=new ObjectId(),dbdata={members:[{_id:id,email:'15003',name:'Test',password:await bcrypt.hash('original-password',4),membershipEndDate:'2099-01-01'}],member_passkeys:[],member_passkey_challenges:[]};const db={collection:n=>({findOne:async q=>dbdata[n].find(d=>match(d,q)),find:q=>({toArray:async()=>dbdata[n].filter(d=>match(d,q))}),insertOne:async d=>{d._id??=new ObjectId();dbdata[n].push(d);},findOneAndDelete:async q=>{const i=dbdata[n].findIndex(d=>match(d,q));return i<0?null:dbdata[n].splice(i,1)[0];},updateOne:async(q,u)=>{const d=dbdata[n].find(d=>match(d,q));if(d)Object.assign(d,u.$set);return {matchedCount:d?1:0,modifiedCount:d?1:0};},deleteOne:async q=>{dbdata[n]=dbdata[n].filter(d=>!match(d,q));}})};
 let verification=true;const wa={generateRegistrationOptions:async opts=>{assert.equal(opts.authenticatorSelection.userVerification,'required');return {challenge:'reg-challenge'};},verifyRegistrationResponse:async opts=>{assert.equal(opts.expectedChallenge,'reg-challenge');assert.equal(opts.expectedRPID,'www.socialclubamsterdam.com');assert.equal(opts.requireUserVerification,true);return {verified:verification,registrationInfo:{credentialID:'credential',credentialPublicKey:new Uint8Array([1]),counter:0}};},generateAuthenticationOptions:async()=>({challenge:'login-challenge'}),verifyAuthenticationResponse:async opts=>{assert.equal(opts.expectedChallenge,'login-challenge');assert.equal(opts.requireUserVerification,true);assert.deepEqual(opts.expectedOrigin,['https://www.socialclubamsterdam.com']);assert.equal(opts.authenticator.credentialID,'credential');return {verified:verification,authenticationInfo:{newCounter:1}};}};
 const app=express();app.use(express.json());app.use(memberAccountRouter({getDB:()=>db,isStaff,authenticateToken:(req,res,next)=>{const who=req.headers.authorization;if(!who)return res.sendStatus(401);req.user={id:who};next();},generateToken:m=>{assert.equal(m.role,undefined);return 'member-token';},authLimiter:(req,res,next)=>next(),config:{rpID:'www.socialclubamsterdam.com',origin:['https://www.socialclubamsterdam.com'],rpName:'Amsterdam'},wa:real?realWA:wa}));return {app,id,other,dbdata,setVerification:v=>verification=v};}
test('member settings reject anonymous/staff and whitelist contact fields',async()=>{const f=await fixture();assert.equal((await request(f.app).get('/')).status,401);assert.equal((await request(f.app).get('/').set('Authorization','admin')).status,403);assert.equal((await request(f.app).patch('/').set('Authorization',String(f.id)).send({contactEmail:'test@example.com',phone:'+34600000000',role:'super_admin',balance:1000})).status,200);assert.equal(f.dbdata.members[0].role,undefined);assert.equal(f.dbdata.members[0].balance,undefined);});
test('password changes require member authentication, not the old password, and reject short replacements',async()=>{const f=await fixture(),send=b=>request(f.app).post('/password').set('Authorization',String(f.id)).send(b);assert.equal((await request(f.app).post('/password').send({newPassword:'replacement-password'})).status,401);assert.equal((await send({newPassword:'short'})).status,400);assert.equal((await send({newPassword:'replacement-password'})).status,200);assert.ok(await bcrypt.compare('replacement-password',f.dbdata.members[0].password));});
test('passkeys bind enrollment to owner, consume challenge once and reject replay/invalid proof/expired members',async()=>{const f=await fixture(),auth=r=>r.set('Authorization',String(f.id));assert.equal((await request(f.app).post('/passkeys/register-options').send({name:'Phone'})).status,401);let r=await auth(request(f.app).post('/passkeys/register-options')).send({name:'Phone'});const challengeId=r.body.challengeId;assert.equal(r.status,200);r=await auth(request(f.app).post('/passkeys/register')).send({challengeId,credential:{}});assert.equal(r.status,200);assert.equal((await auth(request(f.app).post('/passkeys/register')).send({challengeId,credential:{}})).status,400);
 const login=async()=>{const o=await request(f.app).post('/passkeys/login-options').send({});return request(f.app).post('/passkeys/login').send({challengeId:o.body.challengeId,credential:{id:'credential',response:{userHandle:Buffer.from('member:'+f.id).toString('base64url')}}});};f.setVerification(false);assert.equal((await login()).status,401);f.setVerification(true);assert.equal((await login()).body.token,'member-token');f.dbdata.members[0].membershipEndDate='2000-01-01';assert.equal((await login()).status,403);
 f.dbdata.member_passkeys.push({_id:f.other,memberId:'another-member'});await auth(request(f.app).delete('/passkeys/'+f.other));assert.ok(f.dbdata.member_passkeys.find(k=>k._id===f.other));
});
test('real WebAuthn registration and signed authentication; wrong origin and signature rejected',async()=>{
 const f=await fixture(true),auth=r=>r.set('Authorization',String(f.id)),origin='https://www.socialclubamsterdam.com',rpHash=crypto.createHash('sha256').update('www.socialclubamsterdam.com').digest();
 const {privateKey,publicKey}=crypto.generateKeyPairSync('ec',{namedCurve:'prime256v1'}),jwk=publicKey.export({format:'jwk'}),id=crypto.randomBytes(32),idString=id.toString('base64url');
 const cose=encodeCBOR(new Map([[1,2],[3,-7],[-1,1],[-2,new Uint8Array(Buffer.from(jwk.x,'base64url'))],[-3,new Uint8Array(Buffer.from(jwk.y,'base64url'))]]));
 const data=(type,challenge,site=origin)=>Buffer.from(JSON.stringify({type,challenge,origin:site}));
 const o=(await auth(request(f.app).post('/passkeys/register-options')).send({name:'Synthetic authenticator'})).body;
 const len=Buffer.alloc(2);len.writeUInt16BE(id.length);const att=encodeCBOR(new Map([['fmt','none'],['attStmt',new Map()],['authData',new Uint8Array(Buffer.concat([rpHash,Buffer.from([0x45]),Buffer.alloc(4),Buffer.alloc(16),len,id,Buffer.from(cose)]))]]));
 const reg=await auth(request(f.app).post('/passkeys/register')).send({challengeId:o.challengeId,credential:{id:idString,rawId:idString,type:'public-key',response:{attestationObject:Buffer.from(att).toString('base64url'),clientDataJSON:data('webauthn.create',o.options.challenge).toString('base64url')}}});assert.equal(reg.status,200,JSON.stringify(reg.body));
 async function login(site=origin,corrupt=false){const options=(await request(f.app).post('/passkeys/login-options').send({})).body;const client=data('webauthn.get',options.options.challenge,site),count=Buffer.alloc(4);count.writeUInt32BE(1);const ad=Buffer.concat([rpHash,Buffer.from([5]),count]);let sig=crypto.sign('sha256',Buffer.concat([ad,crypto.createHash('sha256').update(client).digest()]),privateKey);if(corrupt)sig[10]^=255;return request(f.app).post('/passkeys/login').send({challengeId:options.challengeId,credential:{id:idString,rawId:idString,type:'public-key',response:{clientDataJSON:client.toString('base64url'),authenticatorData:ad.toString('base64url'),signature:sig.toString('base64url'),userHandle:Buffer.from('member:'+f.id).toString('base64url')}}});}
 assert.equal((await login('https://wrong.example')).status,401);assert.equal((await login(origin,true)).status,401);const signed=await login();assert.equal(signed.status,200,JSON.stringify(signed.body));assert.equal(signed.body.token,'member-token');
});
