import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';import supertest from 'supertest';import crypto from 'node:crypto';
import {MongoMemoryReplSet} from 'mongodb-memory-server';import {MongoClient} from 'mongodb';
import {retailRouter,setupRetail} from '../retail.js';import {cents,dateRange,total,quantities,localDay} from '../retail-domain.js';
let repl,client,db,api,manager;
const key=()=>crypto.randomUUID();
const send=(path,body,method='post',token=false)=>{let r=api[method](path).set('Authorization','owner');if(token)r=r.set('X-Retail-Manager',manager);return r.send({requestId:key(),...body});};
async function fixture(stock=10){const p=await send('/profiles',{name:'Test staff '+key(),role:'staff'},'post',true);assert.equal(p.status,200,JSON.stringify(p.body));const s=await send('/shifts',{profileId:p.body._id});assert.equal(s.status,200);const product=await send('/products',{name:'Sparkling water',category:'drinks',price:'1.50',unitLabel:'bottle',labels:['Cold']});assert.equal(product.status,200);if(stock)assert.equal((await send('/products/'+product.body._id+'/stock',{delta:stock,reason:'Delivery'})).status,200);return {profile:p.body,shift:s.body,product:product.body};}
before(async()=>{repl=await MongoMemoryReplSet.create({replSet:{count:1},binary:{version:'7.0.14'}});client=new MongoClient(repl.getUri());await client.connect();db=client.db('retail-tests');await setupRetail(db);const app=express();app.use(express.json());app.use('/',retailRouter({getDB:()=>db,client,authenticateToken:(req,res,next)=>{if(!req.headers.authorization)return res.sendStatus(401);req.user={id:req.headers.authorization==='owner'?'admin':req.headers.authorization};next();},isAdmin:req=>req.user.id==='admin'||req.user.id==='other-staff',secret:'retail-test-secret',masterPassword:()=> 'test-master',masterHash:()=>null}));api=supertest(app);const r=await api.post('/manager/unlock').set('Authorization','owner').send({password:'test-master'});assert.equal(r.status,200);manager=r.body.token;});
after(async()=>{await client?.close();await repl?.stop();});

test('all tools require staff and reports require session-bound master unlock',async()=>{assert.equal((await api.get('/products')).status,401);assert.equal((await api.get('/products').set('Authorization','member')).status,403);assert.equal((await api.get('/reports').set('Authorization','owner')).status,403);assert.equal((await api.get('/reports').set('Authorization','other-staff').set('X-Retail-Manager',manager)).status,403);assert.equal((await api.post('/manager/unlock').set('Authorization','owner').send({password:'wrong'})).status,401);assert.equal((await send('/profiles',{name:'Unauthorised'})).status,403);});
test('retrying a cash sale deducts stock once and cannot reuse key for a different sale',async()=>{const f=await fixture();const body={requestId:key(),shiftId:f.shift._id,lines:[{productId:f.product._id,quantity:2}]};const a=await send('/sales',body),b=await send('/sales',body);assert.equal(a.status,200);assert.equal(a.body._id,b.body._id);assert.equal(a.body.totalCents,300);assert.equal((await db.collection('retail_products').findOne({_id:f.product._id})).stock,8);assert.equal((await send('/sales',{...body,lines:[{productId:f.product._id,quantity:3}]})).status,409);});
test('concurrent sales cannot oversell the final unit',async()=>{const f=await fixture(1);const results=await Promise.all([1,2].map(()=>send('/sales',{shiftId:f.shift._id,lines:[{productId:f.product._id,quantity:1}]})));assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);assert.equal((await db.collection('retail_products').findOne({_id:f.product._id})).stock,0);});
test('editing a sale returns stock, keeps price snapshot, tracks history, and rejects stale revisions',async()=>{const f=await fixture();const sale=await send('/sales',{shiftId:f.shift._id,lines:[{productId:f.product._id,quantity:3}]});await db.collection('retail_products').updateOne({_id:f.product._id},{$set:{priceCents:999}});const edit=await send('/sales/'+sale.body._id,{revision:1,reason:'Returned one bottle',lines:[{productId:f.product._id,quantity:2}]},'patch');assert.equal(edit.status,200);assert.equal(edit.body.totalCents,300);assert.equal(edit.body.cashDifferenceCents,-150);assert.equal((await db.collection('retail_products').findOne({_id:f.product._id})).stock,8);assert.equal((await send('/sales/'+sale.body._id,{revision:1,reason:'Stale',lines:[]},'patch')).status,409);const voided=await send('/sales/'+sale.body._id,{revision:2,reason:'Full return',lines:[]},'patch');assert.equal(voided.body.voided,true);assert.equal((await db.collection('retail_products').findOne({_id:f.product._id})).stock,10);assert.equal(await db.collection('retail_sale_history').countDocuments({saleId:sale.body._id}),2);});
test('out-of-stock replacement rolls back the whole correction',async()=>{const f=await fixture(),g=await fixture(0);const sale=await send('/sales',{shiftId:f.shift._id,lines:[{productId:f.product._id,quantity:1}]});const r=await send('/sales/'+sale.body._id,{revision:1,reason:'Replacement',lines:[{productId:g.product._id,quantity:1}]},'patch');assert.equal(r.status,409);assert.equal((await db.collection('retail_products').findOne({_id:f.product._id})).stock,9);assert.equal((await db.collection('retail_sales').findOne({_id:sale.body._id})).revision,1);});
test('closed shifts reject new sales and require manager for corrections; tips are attributed',async()=>{const f=await fixture();const sale=await send('/sales',{shiftId:f.shift._id,lines:[{productId:f.product._id,quantity:1}]});const tipKey=key();await send('/shifts/'+f.shift._id+'/tips',{requestId:tipKey,amount:'2.50'});await send('/shifts/'+f.shift._id+'/tips',{requestId:tipKey,amount:'2.50'});assert.equal((await send('/shifts/'+f.shift._id+'/close',{})).status,200);assert.equal((await send('/sales',{shiftId:f.shift._id,lines:[{productId:f.product._id,quantity:1}]})).status,409);assert.equal((await send('/sales/'+sale.body._id,{revision:1,reason:'Return',lines:[]},'patch')).status,409);assert.equal((await send('/sales/'+sale.body._id,{revision:1,reason:'Manager return',lines:[]},'patch',true)).status,200);const r=await api.get('/reports?from='+localDay()+'&to='+localDay()).set('Authorization','owner').set('X-Retail-Manager',manager);assert.equal(r.status,200);const row=r.body.staff.find(s=>s._id===f.profile._id);assert.equal(row.salesCents,0);assert.equal(row.tipsCents,250);assert.equal(row.tipEntries,1);});
test('stock and sale quantities reject fractions, custom packaging labels remain descriptive',async()=>{const f=await fixture();assert.equal((await send('/products/'+f.product._id+'/stock',{delta:0.5,reason:'Fraction'})).status,400);assert.equal((await send('/sales',{shiftId:f.shift._id,lines:[{productId:f.product._id,quantity:1.5}]})).status,400);assert.equal(f.product.unitLabel,'bottle');assert.deepEqual(f.product.labels,['Cold']);});
test('a stale displayed price rejects checkout without stock changes',async()=>{const f=await fixture();const r=await send('/sales',{shiftId:f.shift._id,lines:[{productId:f.product._id,quantity:1,expectedPriceCents:100}]});assert.equal(r.status,409);assert.equal((await db.collection('retail_products').findOne({_id:f.product._id})).stock,10);});
